# ДЗ по "Библиотеки Python для Data Science: Numpy, Matplotlib, Scikit-learn"

##  Видеоурок 2. Вычисления с помощью Numpy. Работа с данными в Pandas
* Домашнее задание:  
[Практическое задание](https://gbcdn.mrgcdn.ru/uploads/asset/5788493/attachment/61ba828f4889847285070f109c8e3c8d.pdf).


## Тема “Вычисления с помощью Numpy”

In [3]:
# Устанавливаем пакет, если он не установлен
# !pip install numpy

In [1]:
import numpy as np

### Задание 1
Создайте массив Numpy под названием `a` размером 5x2, то есть состоящий из 5 строк
и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6,
8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива
Numpy. Результат запишите в массив `mean_a`, в нем должно быть 2 элемента.

In [6]:
# Создаём два массива Numpy размером 1х5 и изменяем размер на 5х1 (5 строк, -1 столбецов сколько получитья, то есть 1)
first_column = np.array([1, 2, 3, 3, 1]).reshape(5, -1)
second_column = np.array([6, 8, 11, 10, 7]).reshape(5, -1)
# Соединим два столбца
a = np.hstack((first_column, second_column))
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
# Запишем среднее значение по каждому столбцу (axis=0 - считаем по столбцам)
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения
соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно
производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [11]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна
получиться величина _centered_spa. Затем поделите a_centered_sp на N-1, где N - число
наблюдений.

In [17]:
a_centered[:, 0]

array([-1.,  0.,  1.,  1., -1.])

In [26]:
# Вычислим скалярное произведение двух столбцов
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
# Вычислим количество наблюдений (сколько у нас строк)
N = a_centered.shape[0]
# Вычислим результат
result = a_centered_sp / (N - 1)   
result

2.0

### Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся
в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на
N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:  

[Выборочная ковариация и выборочная дисперсия — Студопедия](https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html)  

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с
помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать
транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером
2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом
1.

In [34]:
# Проверим результат с помощью функции cov
check = np.cov(m=a.T)[0, 1]
check

2.0