# ДЗ по "Библиотеки Python для Data Science: Numpy, Matplotlib, Scikit-learn"

##  Видеоурок 2. Вычисления с помощью Numpy. Работа с данными в Pandas
* Домашнее задание:  
[Практическое задание](https://gbcdn.mrgcdn.ru/uploads/asset/5788493/attachment/61ba828f4889847285070f109c8e3c8d.pdf).


## Тема “Вычисления с помощью Numpy”

In [41]:
# Устанавливаем пакет, если он не установлен
# !pip install numpy

In [42]:
import numpy as np

### Задание 1
Создайте массив Numpy под названием `a` размером 5x2, то есть состоящий из 5 строк
и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6,
8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива
Numpy. Результат запишите в массив `mean_a`, в нем должно быть 2 элемента.

In [43]:
# Создаём два массива Numpy размером 1х5 и изменяем размер на 5х1 (5 строк, -1 столбецов сколько получитья, то есть 1)
first_column = np.array([1, 2, 3, 3, 1]).reshape(5, -1)
second_column = np.array([6, 8, 11, 10, 7]).reshape(5, -1)
# Соединим два столбца
a = np.hstack((first_column, second_column))
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [44]:
# Запишем среднее значение по каждому столбцу (axis=0 - считаем по столбцам)
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### Задание 2
Вычислите массив `a_centered`, отняв от значений массива `а` средние значения
соответствующих признаков, содержащиеся в массиве `mean_a`. Вычисление должно
производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [45]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна
получиться величина _centered_spa. Затем поделите a_centered_sp на N-1, где N - число
наблюдений.

In [46]:
# Все значения первого столбца матрицы 
a_centered[:, 0]

array([-1.,  0.,  1.,  1., -1.])

In [47]:
# Вычислим скалярное произведение двух столбцов
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
# Вычислим количество наблюдений (сколько у нас строк)
N = a_centered.shape[0]
# Вычислим результат
result = a_centered_sp / (N - 1)   
result

2.0

### Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся
в массиве `а`. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на
N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:  

[Выборочная ковариация и выборочная дисперсия — Студопедия](https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html)  

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с
помощью функции `np.cov`. В качестве аргумента `m` функция `np.cov` должна принимать
транспонированный массив `a`. В получившейся ковариационной матрице (массив Numpy размером
2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом
1.

In [48]:
# Проверим результат с помощью функции cov
check = np.cov(m=a.T)[0, 1]
check

2.0

## Тема “Работа с данными в Pandas”

In [49]:
# Устанавливаем пакет, если он не установлен
# !pip install pandas

In [50]:
import pandas as pd

### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним `pd`. Создайте датафрейм `authors` со
столбцами `author_id` и `author_name`, в которых соответственно содержатся данные: [1, 2, 3] и
['Тургенев', 'Чехов', 'Островский'].  
Затем создайте датафрейм `book` cо столбцами `author_id`, `book_title` и `price`, в которых соответственно
содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],  
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники']  
Нужны prices!  
[500, 400, 300, 350, 450, 600, 200]  

In [51]:
# Создадим датафрейм autohors
authors = pd.DataFrame()
authors['author_id'] = [1, 2, 3]
authors['author_name'] = ['Тургенев', 'Чехов', 'Островский']
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [52]:
# Создадим датафрейм book
book = pd.DataFrame()
book['author_id'] = [1, 1, 1, 2, 2, 3, 3]
book['book_title'] = ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']
book['price'] = [500, 400, 300, 350, 450, 600, 200]
book

author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200

### Задание 2
Получите датафрейм `authors_price`, соединив дата фреймы `authors` и `books` по полю `author_id`.


In [53]:
# Соединим две таблицы по столбцу 'author_id'
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200

### Задание 3
Создайте датафрейм `top5`, в котором содержатся строки из `authors_price` с пятью самыми дорогими
книгами.

In [54]:
top5 = authors_price.sort_values(by="price", ascending=False).head(5)
top5

author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350

### Задание 4
Создайте датафрейм `authors_stat` на основе информации из `authors_price`. В датафрейме `authors_stat`
должны быть четыре столбца:  
`author_name`, `min_price`, `max_price` и `mean_price`,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя
цена на книги этого автора.


In [55]:
# Создаём датафрейм
authors_stat = pd.DataFrame()
# Группируем по авторам и вычислям 'min', 'max', 'mean' по столбцу 'price'
authors_stat = authors_price.groupby("author_name").agg({'price':['min', 'max', 'mean']})
authors_stat

price            
              min  max   mean
author_name                  
Островский    200  600  400.0
Тургенев      300  500  400.0
Чехов         350  450  400.0

In [56]:
# Фамилия автора это индекс, переведём индекс в колонку
authors_stat.reset_index(inplace=True)
# Сделаем из вложенных колонок одну
authors_stat['min_price'] = authors_stat['price']['min']
authors_stat['max_price'] = authors_stat['price']['max']
authors_stat['mean_price'] = authors_stat['price']['mean']
# Удалим не нужную колонку
authors_stat.drop('price', axis=1, inplace=True)
authors_stat

C:\Users\uc201\AppData\Local\Temp\ipykernel_13640\4136075712.py:8: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  authors_stat.drop('price', axis=1, inplace=True)


author_name min_price max_price mean_price
                                            
0  Островский       200       600      400.0
1    Тургенев       300       500      400.0
2       Чехов       350       450      400.0

### Задание 5**
Создайте новый столбец в датафрейме `authors_price` под названием `cover`, в нем будут располагаться
данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные
из следующего списка:  
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].  

Просмотрите документацию по функции `pd.pivot_table` с помощью вопросительного знака.  

Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте
для этого функцию `pd.pivot_table`. При этом столбцы должны называться "твердая" и "мягкая", а
индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,
при необходимости загрузите библиотеку Numpy.  

Назовите полученный датасет `book_info` и сохраните его в формат `pickle` под названием
`book_info.pkl`. Затем загрузите из этого файла датафрейм и назовите его `book_info2`. Удостоверьтесь,
что датафреймы `book_info` и `book_info2` идентичны.


In [57]:
# Добавим новый столбец
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    500  твердая
1          1    Тургенев                 Рудин    400   мягкая
2          1    Тургенев     Дворянское гнездо    300   мягкая
3          2       Чехов      Толстый и тонкий    350  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    600   мягкая
6          3  Островский  Таланты и поклонники    200   мягкая

In [58]:
?pd.pivot_table

Signature:
pd.pivot_table(
    data: 'DataFrame',
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins: 'bool' = False,
    dropna: 'bool' = True,
    margins_name: 'Hashable' = 'All',
    observed: 'bool | lib.NoDefault' = <no_default>,
    sort: 'bool' = True,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
data : DataFrame
values : list-like or scalar, optional
    Column or columns to aggregate.
index : column, Grouper, array, or list of the previous
    Keys to group by on the pivot table index. If a list is passed,
    it can contain any of the other types (except list). If an array is
    passed, it must be the same length as the data and will be used in
    the same manner as column values.
columns : column, Grouper

In [59]:
# Делаем сводную таблицу
book_info = pd.pivot_table(
    # Наш датафрейм
    authors_price,
    # Выбираем столбец в качестве индекса
    index = 'author_name',
    # Выбираем столбец, значения которого станут новыми столбцами
    columns='cover',
    # Выбираем столбец, значения которого станут значениями в новых столбцах
    values='price',
    # Функция агрегации (суммирование по столбцам)
    aggfunc='sum', 
    # Заменяем отсутствующие значения на 0
    fill_value=0
)
book_info

cover        мягкая  твердая
author_name                 
Островский      800        0
Тургенев        700      500
Чехов             0      800

In [60]:
# Запишем датафрейм в picle файл
book_info.to_pickle('book_info.pkl')
# Прочитаем picle файл
book_info_pkl = pd.read_pickle("book_info.pkl")

In [61]:
# Сравним два датафрейма
book_info == book_info_pkl

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True